export interface Action {
	type: ActionType,
	payload: any
}

export enum ActionType {
	UPDATE_SETTINGS = 'UPDATE_SETTINGS',

	REFRESH_GAMES = 'REFRESH_GAMES',
	ADD_POTENTIAL_GAMES = 'ADD_POTENTIAL_GAMES',
	ADD_PLAYABLE_GAMES = 'ADD_PLAYABLE_GAMES',
	EDIT_PLAYABLE_GAME = 'EDIT_PLAYABLE_GAME',
	REMOVE_PLAYABLE_GAME = 'REMOVE_PLAYABLE_GAME',
	LAUNCH_GAME = 'LAUNCH_GAME',
	STOP_GAME = 'STOP_GAME',
	SELECT_GAME = 'SELECT_GAME',
	SET_POTENTIAL_GAME_TO_ADD = 'SET_POTENTIAL_GAME_TO_ADD',

	OPEN_ADD_GAME_MODAL = 'OPEN_ADD_GAME_MODAL',
	CLOSE_ADD_GAME_MODAL = 'CLOSE_ADD_GAME_MODAL'
}
